name: "Packer checks"
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - "images/**"
      - ".github/workflows/packer-build.yml"
      - "module/runners/templates/**"

env:  
  AWS_REGION: eu-west-1

jobs:
  verify_packer:
    name: Verify packer    
    runs-on: ubuntu-latest
    container:
      image: hashicorp/packer:1.7.8
    strategy:
      matrix:
        image: ["linux-amzn2", "windows-core-2019", "ubuntu-focal"]
    defaults:
      run:
        working-directory: images/${{ matrix.image }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      
      - name: packer init
        run: packer init .

      - name: check packer formatting
        run: packer fmt -recursive -check=true .        

      - name: packer validate
        run: packer validate .
